/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHESecretTGEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "encryptedPredictionOf"
      | "grantDecryption"
      | "hasPrediction"
      | "predictionTimestamp"
      | "submitPrediction"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PredictionSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedPredictionOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDecryption",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPrediction",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictionTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPrediction",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedPredictionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictionTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPrediction",
    data: BytesLike
  ): Result;
}

export namespace PredictionSubmittedEvent {
  export type InputTuple = [predictor: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [predictor: string, timestamp: bigint];
  export interface OutputObject {
    predictor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHESecretTGE extends BaseContract {
  connect(runner?: ContractRunner | null): FHESecretTGE;
  waitForDeployment(): Promise<this>;

  interface: FHESecretTGEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  encryptedPredictionOf: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  grantDecryption: TypedContractMethod<
    [grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  hasPrediction: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  predictionTimestamp: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  submitPrediction: TypedContractMethod<
    [encryptedPrediction: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "encryptedPredictionOf"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantDecryption"
  ): TypedContractMethod<[grantee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasPrediction"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "predictionTimestamp"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitPrediction"
  ): TypedContractMethod<
    [encryptedPrediction: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PredictionSubmitted"
  ): TypedContractEvent<
    PredictionSubmittedEvent.InputTuple,
    PredictionSubmittedEvent.OutputTuple,
    PredictionSubmittedEvent.OutputObject
  >;

  filters: {
    "PredictionSubmitted(address,uint256)": TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
    PredictionSubmitted: TypedContractEvent<
      PredictionSubmittedEvent.InputTuple,
      PredictionSubmittedEvent.OutputTuple,
      PredictionSubmittedEvent.OutputObject
    >;
  };
}
